package com.moodify.app.ui.screens

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBackIos
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.moodify.app.R
import com.moodify.app.ui.theme.*

@Deprecated("PHASE2_FROZEN (MFY-PHASE1-FREEZE-001): creator center is Phase II, unreachable from primary navigation")
@Composable
fun CreatorCenterScreen(onBack: () -> Unit, onUpload: () -> Unit) {
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal = 18.dp)) {
        Spacer(Modifier.height(12.dp)); Row(verticalAlignment = Alignment.CenterVertically) { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Outlined.ArrowBackIos, stringResource(R.string.common_back)) }; Text(stringResource(R.string.nav_creator_center), Modifier.weight(1f), color = MoodifyNavy, fontSize = 22.sp, textAlign = androidx.compose.ui.text.style.TextAlign.Center); IconButton(onClick = {}) { Icon(Icons.Outlined.Settings, stringResource(R.string.nav_settings)) } }
        Spacer(Modifier.height(12.dp)); Header(); Spacer(Modifier.height(14.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) { Action(Icons.Outlined.CloudUpload, stringResource(R.string.creator_action_upload), stringResource(R.string.creator_action_upload_desc), Modifier.weight(1f), onUpload); Action(Icons.Outlined.Inventory2, stringResource(R.string.creator_action_drafts), stringResource(R.string.creator_action_drafts_desc), Modifier.weight(1f)) {} }
        Spacer(Modifier.height(18.dp)); Title(stringResource(R.string.creator_overview)); Spacer(Modifier.height(9.dp)); Row(horizontalArrangement = Arrangement.spacedBy(7.dp)) { Overview(Icons.Outlined.Send, stringResource(R.string.creator_overview_pending), "3", Modifier.weight(1f)); Overview(Icons.Outlined.GraphicEq, stringResource(R.string.creator_overview_processing), "1", Modifier.weight(1f)); Overview(Icons.Outlined.Schedule, stringResource(R.string.creator_overview_review), "2", Modifier.weight(1f)); Overview(Icons.Outlined.VerifiedUser, stringResource(R.string.creator_overview_copyright), "6", Modifier.weight(1f)) }
        Spacer(Modifier.height(18.dp)); Title(stringResource(R.string.home_recent_works)); Spacer(Modifier.height(8.dp)); Works()
        Spacer(Modifier.height(18.dp)); Title(stringResource(R.string.creator_trends)); Spacer(Modifier.height(8.dp)); Trend()
        Spacer(Modifier.height(18.dp)); Title(stringResource(R.string.creator_services), false); Spacer(Modifier.height(8.dp)); Row(horizontalArrangement = Arrangement.spacedBy(7.dp)) { Service(Icons.Outlined.VerifiedUser, stringResource(R.string.creator_service_copyright), stringResource(R.string.creator_service_copyright_desc), Modifier.weight(1f)); Service(Icons.Outlined.Groups, stringResource(R.string.nav_partnership), stringResource(R.string.creator_service_collab_desc), Modifier.weight(1f)); Service(Icons.Outlined.BarChart, stringResource(R.string.nav_data_center), stringResource(R.string.creator_service_data_desc), Modifier.weight(1f)) }
        Spacer(Modifier.height(22.dp))
    }
}

@Composable private fun Header() { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(22.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(4.dp)) { Column(Modifier.padding(18.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Box(Modifier.size(78.dp).background(Brush.linearGradient(listOf(Color(0xFFC8C4FF), Color(0xFFE8D7FF))), CircleShape), contentAlignment = Alignment.Center) { Icon(Icons.Outlined.Person, null, tint = Color(0xFF2A226B), modifier = Modifier.size(54.dp)) }; Column(Modifier.padding(start = 15.dp)) { Text("泫榛  ✦", color = MoodifyNavy, fontSize = 21.sp, fontWeight = FontWeight.Bold); Surface(color = MoodifyLavender, shape = RoundedCornerShape(7.dp)) { Text(stringResource(R.string.creator_badge), color = MoodifyPurple, fontSize = 10.sp, modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp)) }; Text(stringResource(R.string.creator_motto), color = MoodifyMuted, fontSize = 11.sp, modifier = Modifier.padding(top = 7.dp)) } }; Spacer(Modifier.height(18.dp)); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceAround) { Stat(stringResource(R.string.profile_stat_works), "24"); Div(); Stat(stringResource(R.string.creator_stat_plays), "128.6万"); Div(); Stat(stringResource(R.string.creator_stat_followers), "1.2万"); Div(); Stat(stringResource(R.string.creator_stat_new_month), "328") } } } }
@Composable private fun Action(icon: ImageVector, title: String, subtitle: String, modifier: Modifier, click: () -> Unit) { Card(onClick = click, modifier = modifier.height(98.dp), shape = RoundedCornerShape(19.dp), colors = CardDefaults.cardColors(containerColor = Color.Transparent)) { Row(Modifier.fillMaxSize().background(Brush.horizontalGradient(listOf(MoodifyBlue, MoodifyPurple)), RoundedCornerShape(19.dp)).padding(14.dp), verticalAlignment = Alignment.CenterVertically) { Box(Modifier.size(45.dp).background(Color.White, RoundedCornerShape(14.dp)), contentAlignment = Alignment.Center) { Icon(icon, null, tint = MoodifyBlue) }; Column(Modifier.padding(start = 10.dp).weight(1f)) { Text(title, color = Color.White, fontSize = 15.sp, fontWeight = FontWeight.Bold); Text(subtitle, color = Color.White.copy(.8f), fontSize = 9.sp) }; Icon(Icons.Outlined.ChevronRight, null, tint = Color.White) } } }
@Composable private fun Overview(icon: ImageVector, label: String, value: String, modifier: Modifier) { Card(modifier, shape = RoundedCornerShape(16.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(3.dp)) { Column(Modifier.fillMaxWidth().padding(vertical = 13.dp), horizontalAlignment = Alignment.CenterHorizontally) { Icon(icon, null, tint = MoodifyPurple, modifier = Modifier.size(22.dp)); Text(label, color = MoodifyMuted, fontSize = 9.sp, modifier = Modifier.padding(top = 6.dp)); Text(value, color = MoodifyNavy, fontSize = 17.sp, fontWeight = FontWeight.Bold) } } }
@Composable private fun Works() { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(19.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(3.dp)) { Column(Modifier.padding(horizontal = 12.dp)) { Work("AI Demo Track", "03:24 · 2025-07-30", "已发布", false); HorizontalDivider(color = MoodifyOutline); Work("Dreamscape", "04:18 · " + stringResource(R.string.creator_updated_at, "2025-07-30"), "草稿", true); HorizontalDivider(color = MoodifyOutline); Work("Sunset Drive", "03:57 · " + stringResource(R.string.creator_updated_at, "2025-07-29"), "处理中", false) } } }
@Composable private fun Work(name: String, date: String, status: String, green: Boolean) { Row(Modifier.fillMaxWidth().padding(vertical = 9.dp), verticalAlignment = Alignment.CenterVertically) { Box(Modifier.size(52.dp).background(Brush.linearGradient(if(green) listOf(Color(0xFF3AB59B), Color(0xFF17495F)) else listOf(Color(0xFF7240D8), Color(0xFF263796))), RoundedCornerShape(9.dp)), contentAlignment = Alignment.Center) { Icon(Icons.Outlined.PlayArrow, null, tint = Color.White) }; Column(Modifier.padding(start = 10.dp).weight(1f)) { Row { Text(name, color = MoodifyNavy, fontSize = 13.sp, fontWeight = FontWeight.SemiBold); Text("  $status", color = MoodifyPurple, fontSize = 8.sp) }; Text(date, color = MoodifyMuted, fontSize = 9.sp); Text("▷ 12.4万   ♡ 2,341   ▢ 342", color = MoodifyMuted, fontSize = 8.sp) }; OutlinedButton(onClick = {}, contentPadding = PaddingValues(horizontal = 11.dp), shape = RoundedCornerShape(16.dp)) { Text(if(status=="草稿") stringResource(R.string.common_edit) else stringResource(R.string.creator_view_data), fontSize = 8.sp) }; Icon(Icons.Outlined.MoreHoriz, null, tint = MoodifyMuted) } }
@Composable private fun Trend() { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(3.dp)) { Row(Modifier.padding(14.dp)) { Column { Text(stringResource(R.string.creator_plays_7d), color = MoodifyMuted, fontSize = 10.sp); Text("24.8K", color = MoodifyNavy, fontSize = 20.sp, fontWeight = FontWeight.Bold); Text(stringResource(R.string.creator_vs_last_week), color = MoodifyGreen, fontSize = 9.sp); Text(stringResource(R.string.creator_new_followers, "128"), color = MoodifyNavy, fontSize = 11.sp, modifier = Modifier.padding(top = 12.dp)) }; Chart(Modifier.padding(start = 12.dp).weight(1f).height(88.dp)) } } }
@Composable private fun Chart(modifier: Modifier) { Canvas(modifier) { val vs=listOf(.2f,.55f,.43f,.72f,.37f,.72f,.9f); val p=Path(); vs.forEachIndexed{i,v->val o=Offset(size.width*i/6,size.height*(1-v));if(i==0)p.moveTo(o.x,o.y)else p.lineTo(o.x,o.y);drawCircle(MoodifyPurple,3.dp.toPx(),o)};drawPath(p,MoodifyPurple,style=androidx.compose.ui.graphics.drawscope.Stroke(2.dp.toPx())) } }
@Composable private fun Service(icon: ImageVector, title: String, sub: String, modifier: Modifier) { Card(onClick = {}, modifier = modifier, shape = RoundedCornerShape(14.dp), colors = CardDefaults.cardColors(containerColor = Color.White)) { Column(Modifier.padding(10.dp)) { Icon(icon, null, tint = MoodifyPurple); Text(title, color = MoodifyNavy, fontSize = 10.sp, fontWeight = FontWeight.Bold); Text(sub, color = MoodifyMuted, fontSize = 7.sp) } } }
@Composable private fun Title(text: String, action: Boolean = true) { Row { Text(text, Modifier.weight(1f), color = MoodifyNavy, fontSize = 18.sp, fontWeight = FontWeight.Bold); if(action) Text(stringResource(R.string.home_view_all), color = MoodifyMuted, fontSize = 10.sp) } }
@Composable private fun Stat(label: String, value: String) { Column(horizontalAlignment = Alignment.CenterHorizontally) { Text(label, color = MoodifyMuted, fontSize = 9.sp); Text(value, color = MoodifyNavy, fontSize = 16.sp, fontWeight = FontWeight.Bold) } }
@Composable private fun Div() { Box(Modifier.width(1.dp).height(39.dp).background(MoodifyOutline)) }
