package com.moodify.app.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBackIos
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.moodify.app.R
import com.moodify.app.ui.components.GradientButton
import com.moodify.app.ui.theme.*

@Composable
fun CopyrightCenterScreen(onBack: () -> Unit, onContinuePublish: () -> Unit) {
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal = 18.dp)) {
        Spacer(Modifier.height(12.dp)); Row(verticalAlignment = Alignment.CenterVertically) { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Outlined.ArrowBackIos, stringResource(R.string.common_back)) }; Text(stringResource(R.string.nav_copyright), Modifier.weight(1f), color = MoodifyNavy, fontSize = 22.sp, fontWeight = FontWeight.Bold, textAlign = androidx.compose.ui.text.style.TextAlign.Center); IconButton(onClick = {}) { Icon(Icons.Outlined.History, stringResource(R.string.copyright_history)) } }
        Spacer(Modifier.height(12.dp)); WorkHeader(); Spacer(Modifier.height(14.dp))
        Row(horizontalArrangement = Arrangement.spacedBy(9.dp)) { MainAction(Icons.Outlined.VerifiedUser, stringResource(R.string.copyright_apply_proof), stringResource(R.string.copyright_apply_proof_desc), true, Modifier.weight(1f)) {}; MainAction(Icons.Outlined.MusicNote, stringResource(R.string.copyright_export_score), stringResource(R.string.copyright_export_score_desc), false, Modifier.weight(1f)) {}; MainAction(Icons.Outlined.Send, stringResource(R.string.copyright_publish), stringResource(R.string.copyright_publish_desc), false, Modifier.weight(1f), onContinuePublish) }
        Spacer(Modifier.height(14.dp)); Section(stringResource(R.string.copyright_status), Icons.Outlined.VerifiedUser) { StatusGrid() }
        Spacer(Modifier.height(14.dp)); Section(stringResource(R.string.copyright_platforms), Icons.Outlined.Podcasts) { Row(horizontalArrangement = Arrangement.spacedBy(7.dp)) { Platform("流媒体 A", "● 已发布", "2024-05-18 10:30", MoodifyPurple, Modifier.weight(1f)); Platform("音乐平台 B", "● 已发布", "2024-05-18 10:30", MoodifyBlue, Modifier.weight(1f)); Platform("创作者频道", "● 同步中", "v1.2 · 85%", MoodifyOrange, Modifier.weight(1f)); Platform("社交发布", "● 待发布", "准备中", MoodifyMuted, Modifier.weight(1f)) } }
        Spacer(Modifier.height(14.dp)); Section(stringResource(R.string.copyright_records), Icons.Outlined.Description) { Record("Version 1.2 · WAV 母版", "当前版本", "2024-05-18 10:30"); HorizontalDivider(color = MoodifyOutline); Record("Version 1.1 · AI Vocal", "", "2024-05-08 16:42"); HorizontalDivider(color = MoodifyOutline); Record("Version 1.0 · Demo", "", "2024-04-28 09:15") }
        Spacer(Modifier.height(14.dp)); Section(stringResource(R.string.copyright_assets), Icons.Outlined.Inventory2) { Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) { Asset(Icons.Outlined.Description, stringResource(R.string.copyright_asset_score), Modifier.weight(1f)); Asset(Icons.Outlined.AudioFile, stringResource(R.string.copyright_asset_midi), Modifier.weight(1f)); Asset(Icons.Outlined.Image, stringResource(R.string.copyright_asset_cover), Modifier.weight(1f)); Asset(Icons.Outlined.Article, stringResource(R.string.copyright_asset_report), Modifier.weight(1f)); Asset(Icons.Outlined.CloudDownload, stringResource(R.string.copyright_asset_metadata), Modifier.weight(1f)) } }
        Spacer(Modifier.height(18.dp)); GradientButton(stringResource(R.string.copyright_continue), onContinuePublish); TextButton(onClick = {}) { Text(stringResource(R.string.copyright_full_archive), color = MoodifyPurple, modifier = Modifier.fillMaxWidth(), textAlign = androidx.compose.ui.text.style.TextAlign.Center) }; Spacer(Modifier.height(20.dp))
    }
}

@Composable private fun WorkHeader() { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(4.dp)) { Row(Modifier.padding(15.dp), verticalAlignment = Alignment.CenterVertically) { Box(Modifier.size(112.dp).background(Brush.linearGradient(listOf(Color(0xFF20265F), Color(0xFF7A5BB5), Color(0xFFF1A8BD))), RoundedCornerShape(13.dp)), contentAlignment = Alignment.Center) { Icon(Icons.Outlined.Landscape, null, tint = Color.White, modifier = Modifier.size(48.dp)) }; Column(Modifier.padding(start = 16.dp).weight(1f)) { Row { Text("Dreamscape", color = MoodifyNavy, fontSize = 21.sp, fontWeight = FontWeight.Bold); Spacer(Modifier.weight(1f)); Surface(color = Color(0xFFE7F8ED), shape = RoundedCornerShape(14.dp)) { Text("● 已发布", color = Color(0xFF2A9E5B), fontSize = 10.sp, modifier = Modifier.padding(horizontal = 10.dp, vertical = 5.dp)) } }; Text("◉ 泫榛", color = MoodifyNavy, fontSize = 11.sp, modifier = Modifier.padding(top = 7.dp)); Text(stringResource(R.string.copyright_work_motto), color = MoodifyMuted, fontSize = 10.sp, modifier = Modifier.padding(top = 6.dp)); Spacer(Modifier.height(13.dp)); Row(horizontalArrangement = Arrangement.spacedBy(24.dp)) { Stat("已确权", "12"); Stat("已发布", "8"); Stat("审核中", "3") } } } } }
@Composable private fun MainAction(icon: ImageVector, title: String, sub: String, primary: Boolean, modifier: Modifier, click: () -> Unit) { Card(onClick = click, modifier = modifier.height(94.dp), shape = RoundedCornerShape(17.dp), colors = CardDefaults.cardColors(containerColor = if(primary) MoodifyPurple else Color.White), elevation = CardDefaults.cardElevation(3.dp)) { Column(Modifier.fillMaxSize().padding(12.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) { Icon(icon, null, tint = if(primary) Color.White else MoodifyPurple, modifier = Modifier.size(27.dp)); Text(title, color = if(primary) Color.White else MoodifyNavy, fontSize = 10.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 5.dp)); Text(sub, color = if(primary) Color.White.copy(.8f) else MoodifyMuted, fontSize = 7.sp) } } }
@Composable private fun Section(title: String, icon: ImageVector, content: @Composable ColumnScope.() -> Unit) { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(3.dp)) { Column(Modifier.padding(13.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Icon(icon, null, tint = MoodifyPurple, modifier = Modifier.size(20.dp)); Text(title, color = MoodifyNavy, fontSize = 16.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(start = 8.dp)) }; Spacer(Modifier.height(10.dp)); content() } } }
@Composable private fun StatusGrid() { Column { Row { Status(Icons.Outlined.CheckCircle, "原创证明", "已填写", MoodifyGreen, Modifier.weight(1f)); Status(Icons.Outlined.EditNote, "封面信息", "已完成", MoodifyBlue, Modifier.weight(1f)) }; HorizontalDivider(color = MoodifyOutline); Row { Status(Icons.Outlined.CheckCircle, "元数据归档", "已填写", MoodifyGreen, Modifier.weight(1f)); Status(Icons.Outlined.Schedule, "发布权限", "审核中", MoodifyOrange, Modifier.weight(1f)) } } }
@Composable private fun Status(icon: ImageVector, title: String, status: String, tint: Color, modifier: Modifier) { Row(modifier.padding(9.dp), verticalAlignment = Alignment.CenterVertically) { Icon(icon, null, tint = tint, modifier = Modifier.size(20.dp)); Text(title, Modifier.padding(start = 8.dp).weight(1f), color = MoodifyNavy, fontSize = 11.sp); Text(status, color = tint, fontSize = 9.sp); Icon(Icons.Outlined.ChevronRight, null, tint = MoodifyMuted, modifier = Modifier.size(17.dp)) } }
@Composable private fun Platform(title: String, status: String, sub: String, tint: Color, modifier: Modifier) { OutlinedCard(onClick = {}, modifier = modifier, shape = RoundedCornerShape(13.dp), border = androidx.compose.foundation.BorderStroke(1.dp, MoodifyOutline)) { Column(Modifier.padding(9.dp)) { Box(Modifier.size(28.dp).background(tint.copy(.12f), CircleShape), contentAlignment = Alignment.Center) { Icon(Icons.Outlined.Share, null, tint = tint, modifier = Modifier.size(16.dp)) }; Text(title, color = MoodifyNavy, fontSize = 9.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 5.dp)); Text(status, color = tint, fontSize = 8.sp); Text(sub, color = MoodifyMuted, fontSize = 7.sp) } } }
@Composable private fun Record(name: String, badge: String, time: String) { Row(Modifier.fillMaxWidth().padding(vertical = 8.dp), verticalAlignment = Alignment.CenterVertically) { Text(name, Modifier.weight(1f), color = MoodifyNavy, fontSize = 11.sp); if(badge.isNotEmpty()) Surface(color = MoodifyLavender, shape = RoundedCornerShape(5.dp)) { Text(badge, color = MoodifyPurple, fontSize = 7.sp, modifier = Modifier.padding(5.dp)) }; Text(time, color = MoodifyMuted, fontSize = 9.sp, modifier = Modifier.padding(start = 8.dp)); Icon(Icons.Outlined.ChevronRight, null, tint = MoodifyMuted, modifier = Modifier.size(17.dp)) } }
@Composable private fun Asset(icon: ImageVector, title: String, modifier: Modifier) { OutlinedCard(onClick = {}, modifier = modifier, shape = RoundedCornerShape(12.dp), border = androidx.compose.foundation.BorderStroke(1.dp, MoodifyOutline)) { Column(Modifier.padding(vertical = 9.dp), horizontalAlignment = Alignment.CenterHorizontally) { Icon(icon, null, tint = MoodifyPurple, modifier = Modifier.size(20.dp)); Text(title, color = MoodifyNavy, fontSize = 7.sp, modifier = Modifier.padding(top = 4.dp)); Text("● 可用", color = MoodifyGreen, fontSize = 7.sp) } } }
@Composable private fun Stat(label: String, value: String) { Column(horizontalAlignment = Alignment.CenterHorizontally) { Text(label, color = MoodifyMuted, fontSize = 9.sp); Text(value, color = MoodifyNavy, fontSize = 17.sp, fontWeight = FontWeight.Bold) } }
