package com.moodify.app.ui.screens

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBackIos
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.moodify.app.ui.components.GradientButton
import com.moodify.app.ui.theme.*

@Composable
fun UploadFlowScreen(onExit: () -> Unit, onProcess: () -> Unit, onPublish: () -> Unit, onLibrary: () -> Unit) {
    var page by remember { mutableIntStateOf(0) }; var selected by remember { mutableStateOf<List<Uri>>(emptyList()) }
    val picker = rememberLauncherForActivityResult(ActivityResultContracts.OpenMultipleDocuments()) { uris -> if (uris.isNotEmpty()) { selected = uris; page = if (uris.size > 1) 2 else 3 } }
    when (page) {
        0 -> UploadEntry(onExit, { picker.launch(arrayOf("audio/*")) }, { page = 1 }, { page = 1 }, { page = 2 })
        1 -> WeChatImport({ page = 0 }, { selected = listOf(Uri.EMPTY, Uri.EMPTY, Uri.EMPTY); page = 2 })
        2 -> BatchUpload({ page = 0 }, selected.ifEmpty { listOf(Uri.EMPTY, Uri.EMPTY, Uri.EMPTY, Uri.EMPTY) }) { page = 3 }
        else -> UploadComplete({ page = 0 }, onProcess, onPublish, onLibrary)
    }
}

@Composable private fun UploadEntry(back: () -> Unit, pick: () -> Unit, record: () -> Unit, cloud: () -> Unit, batch: () -> Unit) {
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp)) {
        Spacer(Modifier.height(12.dp));Header("上传音频",back,Icons.Outlined.HelpOutline);Spacer(Modifier.height(18.dp))
        OutlinedCard(onClick=pick,modifier=Modifier.fillMaxWidth().height(205.dp),shape=RoundedCornerShape(22.dp),border=androidx.compose.foundation.BorderStroke(1.5.dp,MoodifyPurple.copy(.5f))){Column(Modifier.fillMaxSize().background(Color(0xFFF9F8FF)),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Box(Modifier.size(66.dp).background(Brush.linearGradient(listOf(MoodifyPurple,MoodifyBlue)),RoundedCornerShape(18.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.FileUpload,null,tint=Color.White,modifier=Modifier.size(38.dp))};Text("选择音频文件",color=MoodifyNavy,fontSize=19.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=18.dp));Text("支持 WAV / MP3 / FLAC / AAC / M4A，单个不超过 200MB",color=MoodifyMuted,fontSize=10.sp,modifier=Modifier.padding(top=9.dp))}}
        Spacer(Modifier.height(24.dp));Text("推荐来源",color=MoodifyNavy,fontSize=19.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(11.dp));Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){Source(Icons.Outlined.Folder,"本地文件","从手机存储选择",Modifier.weight(1f),pick);Source(Icons.Outlined.Mic,"录音导入","直接录制高质量音频",Modifier.weight(1f),record);Source(Icons.Outlined.Cloud,"微信 / 云端","从微信或云盘导入",Modifier.weight(1f),cloud)}
        Spacer(Modifier.height(23.dp));Text("上传设置",color=MoodifyNavy,fontSize=19.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(9.dp));Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Setting(Icons.Outlined.Tune,"默认处理方式","标准处理");HorizontalDivider(color=MoodifyOutline);Setting(Icons.Outlined.Image,"自动生成封面","开启");HorizontalDivider(color=MoodifyOutline);Setting(Icons.Outlined.ArrowCircleRight,"上传后下一步","进入作品详情")}
        Spacer(Modifier.height(22.dp));Text("你将获得",color=MoodifyNavy,fontSize=18.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(9.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Benefit(Icons.Outlined.GraphicEq,"波形预览","可视化音频内容",Modifier.weight(1f));Benefit(Icons.Outlined.AudioFile,"格式识别","自动识别音频格式",Modifier.weight(1f));Benefit(Icons.Outlined.VerifiedUser,"版权归档支持","提供版权存证服务",Modifier.weight(1f))}
        Spacer(Modifier.height(20.dp));GradientButton("选择音频文件",pick);TextButton(onClick=batch){Text("批量上传",color=MoodifyPurple,modifier=Modifier.fillMaxWidth(),textAlign=androidx.compose.ui.text.style.TextAlign.Center)};Spacer(Modifier.height(20.dp))
    }
}

@Composable private fun WeChatImport(back:()->Unit, import:()->Unit){var selected by remember{mutableStateOf(setOf(0,1,3))};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp)){Spacer(Modifier.height(12.dp));Header("从微信导入",back,Icons.Outlined.HelpOutline);Spacer(Modifier.height(15.dp));Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Color(0xFFF0FBF2))){Row(Modifier.padding(22.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("快速导入微信传输的\n音频与工程文件",color=MoodifyNavy,fontSize=20.sp,fontWeight=FontWeight.Bold);Text("✓ 支持聊天文件\n✓ 支持微信收藏\n✓ 支持批量导入",color=Color(0xFF38B35B),fontSize=11.sp,lineHeight=25.sp,modifier=Modifier.padding(top=15.dp))};Icon(Icons.Outlined.Wechat,null,tint=Color(0xFF42C85A),modifier=Modifier.size(86.dp))}}
Spacer(Modifier.height(12.dp));Row(Modifier.fillMaxWidth().background(Color.White,RoundedCornerShape(14.dp))){listOf("最近接收","聊天文件","微信收藏").forEachIndexed{i,s->Surface(modifier=Modifier.weight(1f),color=if(i==0)Color(0xFFF0FBF2)else Color.Transparent,shape=RoundedCornerShape(13.dp)){Text(s,color=if(i==0)Color(0xFF32A852)else MoodifyMuted,textAlign=androidx.compose.ui.text.style.TextAlign.Center,modifier=Modifier.padding(12.dp))}}};Row(Modifier.padding(vertical=12.dp),horizontalArrangement=Arrangement.spacedBy(7.dp)){TagGreen("全部");FilterButton("仅显示音频");FilterButton("仅显示工程文件")}
Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Column(Modifier.padding(horizontal=12.dp)){listOf("Dreamscape_demo.wav" to "24.6 MB · WAV","AI Vocal Pack.zip" to "128.7 MB · ZIP","Sunset Drive.mid" to "3.2 MB · MIDI","Moodify Project.m4a" to "16.1 MB · M4A").forEachIndexed{i,item->FileRow(item.first,item.second,i in selected){selected=if(i in selected)selected-i else selected+i};if(i<3)HorizontalDivider(color=MoodifyOutline)}}};Spacer(Modifier.height(14.dp));Text("导入设置",color=MoodifyNavy,fontSize=18.sp,fontWeight=FontWeight.Bold);Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Setting(Icons.Outlined.Settings,"默认处理方式","AI 智能增强");Setting(Icons.Outlined.ArrowCircleRight,"上传后下一步","进入作品详情");Setting(Icons.Outlined.Image,"自动生成封面","开启")};Spacer(Modifier.height(15.dp));Text("已选择 ${selected.size} 个文件 · 预计导入约 30 秒",color=MoodifyNavy,fontSize=12.sp);Spacer(Modifier.height(12.dp));GradientButton("导入所选文件",import);TextButton(onClick=back){Text("返回上传入口",color=MoodifyPurple,modifier=Modifier.fillMaxWidth(),textAlign=androidx.compose.ui.text.style.TextAlign.Center)};Spacer(Modifier.height(20.dp))}}

@Composable private fun BatchUpload(back:()->Unit,uris:List<Uri>,start:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp)){Spacer(Modifier.height(12.dp));Header("批量上传",back,Icons.Outlined.FolderOpen);Spacer(Modifier.height(15.dp));Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Color(0xFFF3F1FF))){Row(Modifier.padding(20.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(54.dp).background(MoodifyPurple,RoundedCornerShape(14.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.FileCopy,null,tint=Color.White)};Column(Modifier.padding(start=14.dp)){Text("已选择 ${uris.size.coerceAtLeast(4)} 个作品",color=MoodifyNavy,fontSize=20.sp,fontWeight=FontWeight.Bold);Text("总大小 186MB   ·   预计用时 1 分钟",color=MoodifyPurple,fontSize=13.sp,modifier=Modifier.padding(top=13.dp))}}};Spacer(Modifier.height(14.dp));listOf("Dreamscape" to "上传中 68%","Sunset Drive" to "等待上传","Midnight Walk" to "已完成","AI Demo Track" to "待处理").forEachIndexed{i,item->BatchRow(i+1,item.first,item.second)};Spacer(Modifier.height(18.dp));Text("批量操作",color=MoodifyNavy,fontSize=18.sp,fontWeight=FontWeight.Bold);Row(Modifier.padding(top=9.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Benefit(Icons.Outlined.GraphicEq,"统一处理","设置相同处理方式",Modifier.weight(1f));Benefit(Icons.Outlined.Sell,"统一标签","设置相同标签",Modifier.weight(1f));Benefit(Icons.Outlined.Description,"保存草稿","保存队列",Modifier.weight(1f))};Spacer(Modifier.height(20.dp));GradientButton("开始批量上传",start);TextButton(onClick=back){Text("仅保存队列",color=MoodifyPurple,modifier=Modifier.fillMaxWidth(),textAlign=androidx.compose.ui.text.style.TextAlign.Center)};Spacer(Modifier.height(20.dp))}}

@Composable private fun UploadComplete(back:()->Unit,process:()->Unit,publish:()->Unit,library:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal=18.dp)){Spacer(Modifier.height(12.dp));Header("上传完成",back,Icons.Outlined.History);Spacer(Modifier.height(18.dp));Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=Color(0xFFF3F1FF))){Row(Modifier.padding(25.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("作品已成功导入",color=MoodifyNavy,fontSize=24.sp,fontWeight=FontWeight.Bold);Text("你可以选择下一步，让作品继续成长",color=MoodifyMuted,fontSize=13.sp,modifier=Modifier.padding(top=9.dp))};Box(Modifier.size(78.dp).background(MoodifyPurple,CircleShape),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Check,null,tint=Color.White,modifier=Modifier.size(46.dp))}}};Spacer(Modifier.height(15.dp));Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(105.dp).background(Brush.linearGradient(listOf(Color(0xFF423194),Color(0xFFA96ADA))),RoundedCornerShape(14.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Landscape,null,tint=Color.White,modifier=Modifier.size(44.dp))};Column(Modifier.padding(start=16.dp).weight(1f)){Text("Dreamscape",color=MoodifyNavy,fontSize=21.sp,fontWeight=FontWeight.Bold);Text("♙ 泫榛",color=MoodifyMuted,fontSize=12.sp,modifier=Modifier.padding(top=8.dp));Text("◷ 03:48",color=MoodifyMuted,fontSize=12.sp,modifier=Modifier.padding(top=12.dp))};Surface(color=Color(0xFFE7F8ED),shape=RoundedCornerShape(12.dp)){Text("✓ 已导入",color=MoodifyGreen,modifier=Modifier.padding(10.dp))}}};Spacer(Modifier.height(21.dp));Text("下一步操作",color=MoodifyNavy,fontSize=19.sp,fontWeight=FontWeight.Bold);Row(Modifier.padding(top=10.dp),horizontalArrangement=Arrangement.spacedBy(9.dp)){Next(Icons.Outlined.GraphicEq,"去处理","优化音质与平台适配",Modifier.weight(1f),process);Next(Icons.Outlined.Send,"去发布","填写信息并公开分享",Modifier.weight(1f),publish)};Row(Modifier.padding(top=9.dp),horizontalArrangement=Arrangement.spacedBy(9.dp)){Next(Icons.Outlined.Description,"保存草稿","稍后继续编辑",Modifier.weight(1f),back);Next(Icons.Outlined.AudioFile,"进入作品库","查看已导入作品",Modifier.weight(1f),library)};Spacer(Modifier.height(15.dp));Setting(Icons.Outlined.Lightbulb,"智能建议","这首作品适合先进行标准处理，再发布到创作者主页");Spacer(Modifier.height(18.dp));GradientButton("前往发布",publish);TextButton(onClick=back){Text("返回上传入口",color=MoodifyPurple,modifier=Modifier.fillMaxWidth(),textAlign=androidx.compose.ui.text.style.TextAlign.Center)};Spacer(Modifier.height(20.dp))}}

@Composable private fun Header(title:String,back:()->Unit,icon:ImageVector){Row(verticalAlignment=Alignment.CenterVertically){IconButton(onClick=back){Icon(Icons.AutoMirrored.Outlined.ArrowBackIos,"返回")};Text(title,Modifier.weight(1f),color=MoodifyNavy,fontSize=22.sp,fontWeight=FontWeight.Bold,textAlign=androidx.compose.ui.text.style.TextAlign.Center);IconButton(onClick={}){Icon(icon,null)}}}
@Composable private fun Source(icon:ImageVector,title:String,sub:String,modifier:Modifier,click:()->Unit){Card(onClick=click,modifier=modifier.height(138.dp),shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=Color.White),elevation=CardDefaults.cardElevation(3.dp)){Column(Modifier.padding(14.dp)){Icon(icon,null,tint=MoodifyPurple,modifier=Modifier.size(36.dp));Spacer(Modifier.weight(1f));Text(title,color=MoodifyNavy,fontSize=14.sp,fontWeight=FontWeight.Bold);Text(sub,color=MoodifyMuted,fontSize=9.sp)}}}
@Composable private fun Setting(icon:ImageVector,title:String,value:String){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=MoodifyPurple);Text(title,Modifier.padding(start=11.dp).weight(1f),color=MoodifyNavy,fontSize=13.sp);Text(value,color=MoodifyMuted,fontSize=11.sp);Icon(Icons.Outlined.ChevronRight,null,tint=MoodifyMuted)}}
@Composable private fun Benefit(icon:ImageVector,title:String,sub:String,modifier:Modifier){Card(modifier,shape=RoundedCornerShape(15.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Row(Modifier.padding(11.dp)){Icon(icon,null,tint=MoodifyPurple);Column(Modifier.padding(start=8.dp)){Text(title,color=MoodifyNavy,fontSize=10.sp,fontWeight=FontWeight.Bold);Text(sub,color=MoodifyMuted,fontSize=7.sp)}}}}
@Composable private fun FileRow(name:String,meta:String,checked:Boolean,toggle:()->Unit){Row(Modifier.fillMaxWidth().padding(vertical=11.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(name.endsWith("zip"))Icons.Outlined.FolderZip else Icons.Outlined.AudioFile,null,tint=if(name.endsWith("zip"))MoodifyOrange else MoodifyPurple,modifier=Modifier.size(39.dp));Column(Modifier.padding(start=12.dp).weight(1f)){Text(name,color=MoodifyNavy,fontSize=13.sp);Text(meta,color=MoodifyMuted,fontSize=9.sp,modifier=Modifier.padding(top=4.dp))};Checkbox(checked,toggle,colors=CheckboxDefaults.colors(checkedColor=Color(0xFF3BB35A)))}}
@Composable private fun BatchRow(n:Int,name:String,status:String){Card(Modifier.fillMaxWidth().padding(bottom=9.dp),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Row(Modifier.padding(13.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(70.dp).background(Brush.linearGradient(listOf(MoodifyPurple,MoodifyBlue)),RoundedCornerShape(10.dp)),contentAlignment=Alignment.TopStart){Text("$n",color=Color.White,modifier=Modifier.padding(5.dp))};Column(Modifier.padding(start=14.dp).weight(1f)){Text(name,color=MoodifyNavy,fontSize=17.sp,fontWeight=FontWeight.Bold);Text("WAV · 03:42 · 48MB",color=MoodifyMuted,fontSize=10.sp);Text(status,color=if(status.contains("完成"))MoodifyGreen else if(status.contains("待处理"))MoodifyOrange else MoodifyPurple,fontSize=11.sp,modifier=Modifier.padding(top=7.dp));if(status.contains("68"))LinearProgressIndicator(progress={.68f},modifier=Modifier.fillMaxWidth().padding(top=5.dp),color=MoodifyPurple,trackColor=MoodifyOutline)};Icon(Icons.Outlined.DragHandle,null,tint=MoodifyMuted)}}}
@Composable private fun Next(icon:ImageVector,title:String,sub:String,modifier:Modifier,click:()->Unit){Card(onClick=click,modifier=modifier.height(92.dp),shape=RoundedCornerShape(17.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Row(Modifier.fillMaxSize().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=MoodifyPurple,modifier=Modifier.size(32.dp));Column(Modifier.padding(start=11.dp).weight(1f)){Text(title,color=MoodifyNavy,fontSize=14.sp,fontWeight=FontWeight.Bold);Text(sub,color=MoodifyMuted,fontSize=9.sp)};Icon(Icons.Outlined.ChevronRight,null,tint=MoodifyMuted)}}}
@Composable private fun TagGreen(text:String){Surface(color=Color(0xFFE8F8EC),shape=RoundedCornerShape(15.dp)){Text(text,color=Color(0xFF35A953),modifier=Modifier.padding(horizontal=12.dp,vertical=7.dp))}}
@Composable private fun FilterButton(text:String){OutlinedButton(onClick={},shape=RoundedCornerShape(15.dp),contentPadding=PaddingValues(horizontal=11.dp)){Text(text,color=MoodifyMuted,fontSize=9.sp)}}
