#!/usr/bin/env python3
"""Extract per-loop DeepSeek v4 worker tasks from a last-night metric snapshot.

One script serving three MHPs:
  MHP-798 — runtime_reliability loop
  MHP-799 — scoring_calibration loop
  MHP-800 — craft_preset_selection loop

Each loop produces a standalone JSONL file ready for DeepSeek v4 one-record-per-call
processing. The operator_report loop is always generated by the runbook and is not
split here.

Part of ECHAIN-MOODIFY-DATA-LOOP-014 / Probe Plan-6B.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

LOOP_CONFIGS: dict[str, dict[str, Any]] = {
    "runtime_reliability": {
        "mhp": "MHP-798",
        "description": "One run-level task when fatal errors or failures exist",
        "predicate": "fatal_or_failed",
        "task_id_suffix": "runtime",
        "instruction": "Classify runtime severity and give one next action.",
        "input_type": "run_record",
        "data_fields": ["run_id", "success", "failed", "fatal_error"],
    },
    "scoring_calibration": {
        "mhp": "MHP-799",
        "description": "One task per pseudo/MRS Open sign disagreement",
        "predicate": "row_disagreement",
        "task_id_suffix": "score",
        "instruction": "Classify scoring disagreement severity and give one calibration action.",
        "input_type": "task_record",
        "data_fields": ["task_id", "sample_id", "preset", "pseudo_delta_mrs",
                        "delta_mrs_open_v031", "score_direction_disagreement"],
    },
    "craft_preset_selection": {
        "mhp": "MHP-800",
        "description": "One task per preset result that triggered a penalty flag",
        "predicate": "row_flagged",
        "task_id_suffix": "craft",
        "instruction": "Classify preset risk and give one craft/preset action.",
        "input_type": "task_record",
        "data_fields": ["task_id", "sample_id", "preset", "delta_mrs_open_v031",
                        "mrs_open_flags"],
    },
}


def load_snapshot(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def extract_runtime_task(snapshot: dict[str, Any]) -> dict[str, Any] | None:
    """Extract one runtime_reliability task if fatal error or failures exist."""
    run_id = snapshot.get("source_run", "")
    fatal = snapshot.get("fatal_error")
    failed = snapshot.get("failed") or 0
    if not fatal and not failed:
        return None
    return {
        "task_id": f"{run_id}:runtime",
        "loop": "runtime_reliability",
        "input_type": "run_record",
        "data": {
            "run_id": run_id,
            "success": snapshot.get("success"),
            "failed": failed,
            "fatal_error": fatal,
        },
        "instruction": "Classify runtime severity and give one next action.",
    }


def extract_scoring_tasks(snapshot: dict[str, Any]) -> list[dict[str, Any]]:
    """Extract one scoring_calibration task per sign disagreement."""
    tasks: list[dict[str, Any]] = []
    for row in snapshot.get("tasks", []):
        if not row.get("score_direction_disagreement"):
            continue
        tasks.append({
            "task_id": f"{row['task_id']}:score",
            "loop": "scoring_calibration",
            "input_type": "task_record",
            "data": {
                "task_id": row["task_id"],
                "sample_id": row["sample_id"],
                "preset": row["preset"],
                "pseudo_delta_mrs": row["pseudo_delta_mrs"],
                "delta_mrs_open_v031": row["delta_mrs_open_v031"],
                "score_direction_disagreement": row["score_direction_disagreement"],
            },
            "instruction": "Classify scoring disagreement severity and give one calibration action.",
        })
    return tasks


def extract_craft_tasks(snapshot: dict[str, Any]) -> list[dict[str, Any]]:
    """Extract one craft_preset_selection task per penalty flag."""
    tasks: list[dict[str, Any]] = []
    for row in snapshot.get("tasks", []):
        if not row.get("mrs_open_flags"):
            continue
        tasks.append({
            "task_id": f"{row['task_id']}:craft",
            "loop": "craft_preset_selection",
            "input_type": "task_record",
            "data": {
                "task_id": row["task_id"],
                "sample_id": row["sample_id"],
                "preset": row["preset"],
                "delta_mrs_open_v031": row["delta_mrs_open_v031"],
                "mrs_open_flags": row["mrs_open_flags"],
            },
            "instruction": "Classify preset risk and give one craft/preset action.",
        })
    return tasks


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for item in records:
            f.write(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n")


def run(snapshot_path: Path, out_dir: Path, loops: list[str] | None = None) -> dict[str, Any]:
    """Extract per-loop JSONL files from the snapshot."""
    snapshot = load_snapshot(snapshot_path)
    results: dict[str, Any] = {}

    if loops is None:
        loops = list(LOOP_CONFIGS)

    for loop in loops:
        config = LOOP_CONFIGS[loop]
        out_path = out_dir / f"{loop}_tasks.jsonl"

        if loop == "runtime_reliability":
            task = extract_runtime_task(snapshot)
            records = [task] if task else []
        elif loop == "scoring_calibration":
            records = extract_scoring_tasks(snapshot)
        elif loop == "craft_preset_selection":
            records = extract_craft_tasks(snapshot)
        else:
            print(f"Unknown loop: {loop}", file=sys.stderr)
            continue

        write_jsonl(out_path, records)
        results[loop] = {"path": str(out_path), "count": len(records), "mhp": config["mhp"]}
        print(f"{config['mhp']}  {loop:30s}  {len(records)} task(s)  → {out_path}")

    return results


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Extract per-loop DeepSeek worker tasks from a metric snapshot"
    )
    parser.add_argument(
        "--snapshot", type=Path, required=True,
        help="Path to last_night_metric_snapshot.json",
    )
    parser.add_argument(
        "--out-dir", type=Path, required=True,
        help="Output directory for per-loop JSONL files",
    )
    parser.add_argument(
        "--loops", nargs="*",
        choices=list(LOOP_CONFIGS),
        help="Specific loops to extract (default: all three)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.snapshot.exists():
        print(f"Error: snapshot not found: {args.snapshot}", file=sys.stderr)
        return 1
    result = run(args.snapshot, args.out_dir, args.loops)
    total = sum(v["count"] for v in result.values())
    print(json.dumps({"total_tasks": total, "loops": {k: v["count"] for k, v in result.items()}}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
