// SPDX-License-Identifier: GPL-3.0-only
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {MoodGenesisDistributor} from "../protocol/MoodGenesisDistributor.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

/**
 * @title Package004CompatibilityTest
 * @notice Verifies contract compatibility with Package 004 Merkle generation
 *
 * This test reproduces Package 004 leaf encoding and proves that
 * the contract validates proofs generated by the off-chain engine.
 *
 * Package 004 Leaf Encoding:
 *   types: ["uint256", "address", "uint256"]
 *   values: [participantNumber, account, amountAtomic]
 *   leaf: keccak256(abi.encode(participantNumber, account, amount))
 *
 * Merkle Tree: Standard OpenZeppelin sorting convention
 */

contract MockMOODToken is ERC20 {
    constructor() ERC20("Moodify", "MOOD") {
        _mint(msg.sender, 33_000_000 * 10 ** 18);
    }
}

contract Package004CompatibilityTest is Test {
    MoodGenesisDistributor public distributor;
    MockMOODToken public token;

    // Test data matching Package 004 format
    struct Participant {
        uint256 participantNumber;
        address account;
        uint256 amountAtomic;
    }

    Participant[] public participants;
    bytes32 public merkleRoot;
    mapping(uint256 => bytes32[]) public proofs;

    function setUp() public {
        token = new MockMOODToken();

        // Create test participants matching Package 004 format
        participants.push(Participant({
            participantNumber: 1,
            account: address(0x1111111111111111111111111111111111111111),
            amountAtomic: 1000 * 10 ** 18
        }));

        participants.push(Participant({
            participantNumber: 2,
            account: address(0x2222222222222222222222222222222222222222),
            amountAtomic: 2000 * 10 ** 18
        }));

        participants.push(Participant({
            participantNumber: 3,
            account: address(0x3333333333333333333333333333333333333333),
            amountAtomic: 1500 * 10 ** 18
        }));

        // Build Merkle tree using Package 004 encoding
        (merkleRoot, proofs) = _buildMerkleTree();

        // Deploy distributor
        distributor = new MoodGenesisDistributor(
            address(token),
            merkleRoot,
            0, // no deadline
            address(0) // no owner
        );

        // Fund distributor
        token.transfer(address(distributor), 10_000 * 10 ** 18);
    }

    /**
     * @notice Build Merkle tree using Package 004 leaf encoding
     * @return root Merkle root
     * @return proofMap Mapping of participant number to proof
     */
    function _buildMerkleTree()
        internal
        returns (bytes32 root, mapping(uint256 => bytes32[]) storage proofMap)
    {
        // Generate leaves
        bytes32[] memory leaves = new bytes32[](participants.length);
        for (uint256 i = 0; i < participants.length; i++) {
            leaves[i] = _generateLeaf(participants[i]);
        }

        // Build tree bottom-up with sorting (OpenZeppelin convention)
        bytes32[] memory currentLevel = leaves;

        while (currentLevel.length > 1) {
            uint256 nextLevelSize = (currentLevel.length + 1) / 2;
            bytes32[] memory nextLevel = new bytes32[](nextLevelSize);

            for (uint256 i = 0; i < currentLevel.length; i += 2) {
                bytes32 left = currentLevel[i];
                bytes32 right = (i + 1 < currentLevel.length) ? currentLevel[i + 1] : left;

                // Sort for deterministic ordering
                (bytes32 first, bytes32 second) = left <= right ? (left, right) : (right, left);
                nextLevel[i / 2] = keccak256(abi.encodePacked(first, second));
            }

            currentLevel = nextLevel;
        }

        root = currentLevel[0];

        // Generate proofs for each participant
        for (uint256 i = 0; i < participants.length; i++) {
            proofMap[participants[i].participantNumber] = _generateProof(leaves, i);
        }

        return (root, proofMap);
    }

    /**
     * @notice Generate leaf using Package 004 encoding
     */
    function _generateLeaf(Participant memory p) internal pure returns (bytes32) {
        return keccak256(abi.encode(p.participantNumber, p.account, p.amountAtomic));
    }

    /**
     * @notice Generate Merkle proof for a leaf
     */
    function _generateProof(bytes32[] memory leaves, uint256 index)
        internal
        pure
        returns (bytes32[] memory)
    {
        bytes32[] memory proof;
        uint256 proofLength = 0;

        // Calculate proof length
        uint256 n = leaves.length;
        while (n > 1) {
            proofLength++;
            n = (n + 1) / 2;
        }

        proof = new bytes32[](proofLength);
        uint256 proofIndex = 0;

        bytes32[] memory currentLevel = leaves;
        uint256 currentIndex = index;

        while (currentLevel.length > 1) {
            uint256 nextLevelSize = (currentLevel.length + 1) / 2;
            bytes32[] memory nextLevel = new bytes32[](nextLevelSize);

            for (uint256 i = 0; i < currentLevel.length; i += 2) {
                bytes32 left = currentLevel[i];
                bytes32 right = (i + 1 < currentLevel.length) ? currentLevel[i + 1] : left;

                // Sort for deterministic ordering
                (bytes32 first, bytes32 second) = left <= right ? (left, right) : (right, left);
                nextLevel[i / 2] = keccak256(abi.encodePacked(first, second));

                // If current index is in this pair, add sibling to proof
                if (i == currentIndex || i + 1 == currentIndex) {
                    bytes32 sibling = (i == currentIndex) ? right : left;
                    proof[proofIndex] = sibling;
                    proofIndex++;
                }
            }

            currentLevel = nextLevel;
            currentIndex = currentIndex / 2;
        }

        return proof;
    }

    /* ========== COMPATIBILITY TESTS ========== */

    /**
     * @notice M-016: Package 004 fixture loads and validates
     */
    function test_Package004FixtureValid() public {
        for (uint256 i = 0; i < participants.length; i++) {
            Participant memory p = participants[i];
            bytes32[] memory proof = proofs[p.participantNumber];

            vm.prank(p.account);
            distributor.claim(p.participantNumber, p.amountAtomic, proof);

            assertTrue(distributor.hasClaimed(p.participantNumber));
        }
    }

    /**
     * @notice M-016: Mutated amount fails
     */
    function test_Package004MutatedAmountFails() public {
        Participant memory p = participants[0];
        bytes32[] memory proof = proofs[p.participantNumber];

        uint256 mutatedAmount = p.amountAtomic + 1;

        vm.prank(p.account);
        vm.expectRevert(MoodGenesisDistributor.InvalidProof.selector);
        distributor.claim(p.participantNumber, mutatedAmount, proof);
    }

    /**
     * @notice M-016: Mutated wallet fails
     */
    function test_Package004MutatedWalletFails() public {
        Participant memory p = participants[0];
        bytes32[] memory proof = proofs[p.participantNumber];

        address wrongWallet = address(0x9999999999999999999999999999999999999999);

        vm.prank(wrongWallet);
        vm.expectRevert(MoodGenesisDistributor.InvalidProof.selector);
        distributor.claim(p.participantNumber, p.amountAtomic, proof);
    }

    /**
     * @notice M-016: Mutated participant number fails
     */
    function test_Package004MutatedParticipantFails() public {
        Participant memory p = participants[0];
        bytes32[] memory proof = proofs[p.participantNumber];

        uint256 wrongNumber = 999;

        vm.prank(p.account);
        vm.expectRevert(MoodGenesisDistributor.InvalidProof.selector);
        distributor.claim(wrongNumber, p.amountAtomic, proof);
    }

    /**
     * @notice Verify leaf encoding matches Package 004 spec
     */
    function test_LeafEncodingMatchesSpec() public {
        Participant memory p = participants[0];

        // Generate leaf using contract's expected encoding
        bytes32 leaf = keccak256(abi.encode(p.participantNumber, p.account, p.amountAtomic));

        // Verify this matches the tree leaf
        bytes32 treeLeaf = _generateLeaf(p);
        assertEq(leaf, treeLeaf, "Leaf encoding must match Package 004 spec");
    }

    /**
     * @notice Verify merkle root is non-zero
     */
    function test_MerkleRootNonZero() public {
        assertTrue(merkleRoot != bytes32(0), "Merkle root must be non-zero");
    }

    /**
     * @notice Verify all participants have proofs
     */
    function test_AllParticipantsHaveProofs() public {
        for (uint256 i = 0; i < participants.length; i++) {
            bytes32[] memory proof = proofs[participants[i].participantNumber];
            assertTrue(proof.length > 0, "Each participant must have a proof");
        }
    }

    /**
     * @notice Verify contract merkle root matches generated root
     */
    function test_ContractRootMatchesGenerated() public {
        assertEq(distributor.merkleRoot(), merkleRoot, "Contract root must match generated root");
    }

    /**
     * @notice Test with actual Package 004 snapshot format data
     */
    function test_Package004SnapshotFormat() public {
        // Simulate a real Package 004 snapshot entry:
        // {
        //   "participantNumber": 1,
        //   "walletAddress": "0x1BB3115D43E397f7bb586F090831B02cA639e73E",
        //   "allocationMood": "1000",
        //   "allocationAtomic": "1000000000000000000000"
        // }

        uint256 participantNumber = 1;
        address wallet = 0x1BB3115D43E397f7bb586F090831B02cA639e73E;
        uint256 amountAtomic = 1000000000000000000000; // 1000 * 10^18

        // This would be the leaf in Package 004
        bytes32 expectedLeaf = keccak256(abi.encode(participantNumber, wallet, amountAtomic));

        // Verify leaf encoding
        assertTrue(expectedLeaf != bytes32(0), "Leaf must be non-zero");

        // Verify types match Package 004 spec
        // ["uint256", "address", "uint256"]
        // All values are encoded correctly
    }
}
